version: "3.9"

services:
  tg_bot:
    image: tg_bot:1
    build:
      context: tg_bot
      dockerfile: DockerfileTgBot
    working_dir: /usr/src/app
    ports:
      - 4001:4001
    volumes:
      - ./tg_bot:/usr/src/app
    secrets:
      - capybara_token

secrets:
  capybara_token:
    external: true
