version: "3.9"
services:
  selenium:
      build: .
      ports:
        - 4000:4000
      volumes:
        - .:/usr/src/app
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      privileged: true
